import type { ThemeCustomConfig, PresetName } from './themeTypes';

export const PRESETS: Record<PresetName, ThemeCustomConfig> = {
  // Glassmorphisme — violet accent, semi-transparent dark
  glass: {
    activePreset: 'glass',
    primaryColor: '#7c3aed',
    bgPrimary: 'rgba(20, 20, 20, 0.82)',
    bgSecondary: 'rgba(30, 30, 30, 0.72)',
    bgInput: 'rgba(255, 255, 255, 0.05)',
    borderColor: 'rgba(255, 255, 255, 0.12)',
    borderRadius: 12,
    shadowEnabled: true,
    textPrimary: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.68)',
    itemBg: 'rgba(0, 0, 0, 0.32)',
    itemBgHover: 'rgba(124, 58, 237, 0.18)',
    notifBg: '',
    notifBorder: '',
    notifTextTitle: '',
    notifTextBody: '',
    progressColor: '',
    circleProgressColor: '',
    skillCheckColor: '#ffffff',
    animationStyle: 'slide',
    animationSpeed: 'normal',
    notificationPosition: 'top-right',
    progressPosition: 'bottom',
    circleProgressPosition: 'bottom',
    textUiPosition: 'auto',
  },

  // Moderne Solide — blue accent, opaque dark with colored border
  solid: {
    activePreset: 'solid',
    primaryColor: '#3b82f6',
    bgPrimary: 'rgba(18, 18, 22, 0.97)',
    bgSecondary: 'rgba(28, 28, 36, 0.97)',
    bgInput: 'rgba(255, 255, 255, 0.06)',
    borderColor: 'rgba(59, 130, 246, 0.30)',
    borderRadius: 10,
    shadowEnabled: true,
    textPrimary: '#f0f0ff',
    textSecondary: 'rgba(220, 220, 255, 0.58)',
    itemBg: 'rgba(255, 255, 255, 0.04)',
    itemBgHover: 'rgba(59, 130, 246, 0.14)',
    notifBg: '',
    notifBorder: '',
    notifTextTitle: '',
    notifTextBody: '',
    progressColor: '',
    circleProgressColor: '',
    skillCheckColor: '#93c5fd',
    animationStyle: 'slide',
    animationSpeed: 'normal',
    notificationPosition: 'top-right',
    progressPosition: 'bottom',
    circleProgressPosition: 'bottom',
    textUiPosition: 'auto',
  },

  // Néon Épuré — purple accent, near-black, neon border
  neon: {
    activePreset: 'neon',
    primaryColor: '#a855f7',
    bgPrimary: 'rgba(8, 8, 20, 0.96)',
    bgSecondary: 'rgba(14, 14, 32, 0.92)',
    bgInput: 'rgba(168, 85, 247, 0.06)',
    borderColor: 'rgba(168, 85, 247, 0.38)',
    borderRadius: 8,
    shadowEnabled: true,
    textPrimary: '#e9d5ff',
    textSecondary: 'rgba(196, 160, 255, 0.62)',
    itemBg: 'rgba(168, 85, 247, 0.08)',
    itemBgHover: 'rgba(168, 85, 247, 0.22)',
    notifBg: '',
    notifBorder: '',
    notifTextTitle: '',
    notifTextBody: '',
    progressColor: '#7c3aed',
    circleProgressColor: '',
    skillCheckColor: '#c084fc',
    animationStyle: 'scale',
    animationSpeed: 'normal',
    notificationPosition: 'top-right',
    progressPosition: 'bottom',
    circleProgressPosition: 'bottom',
    textUiPosition: 'auto',
  },

  // Compact Flat — sky-blue accent, steel dark, flat no-blur
  compact: {
    activePreset: 'compact',
    primaryColor: '#0ea5e9',
    bgPrimary: 'rgba(30, 41, 59, 0.96)',
    bgSecondary: 'rgba(40, 54, 78, 0.92)',
    bgInput: 'rgba(255, 255, 255, 0.05)',
    borderColor: 'rgba(14, 165, 233, 0.25)',
    borderRadius: 6,
    shadowEnabled: false,
    textPrimary: '#f1f5f9',
    textSecondary: 'rgba(203, 213, 225, 0.60)',
    itemBg: 'rgba(255, 255, 255, 0.04)',
    itemBgHover: 'rgba(14, 165, 233, 0.14)',
    notifBg: '',
    notifBorder: '',
    notifTextTitle: '',
    notifTextBody: '',
    progressColor: '',
    circleProgressColor: '',
    skillCheckColor: '#7dd3fc',
    animationStyle: 'slide',
    animationSpeed: 'fast',
    notificationPosition: 'top-right',
    progressPosition: 'bottom',
    circleProgressPosition: 'bottom',
    textUiPosition: 'auto',
  },
};

export function getPreset(name: PresetName): ThemeCustomConfig {
  return { ...PRESETS[name] };
}

export const PRESET_LABELS: Record<PresetName, string> = {
  glass:   '🔷 Glassmorphisme',
  solid:   '🔲 Moderne Solide',
  neon:    '🟣 Néon Épuré',
  compact: '▪️ Compact Flat',
};
